In [63]:
#import numpy as np 
import math
import matplotlib.pyplot as plt
from random import randint
from random import randrange 

In [64]:
a = np.array([10, 5])
print(a)


[10  5]


In [65]:
a = np.zeros([10, 10])
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [71]:
#print(random.random()) #pour donner un nombre decimal aleatoire  
#print(np.random.randint(0,5)) # nombre entier  aleatoire entre 0 et 5
n = [2, 3, 5, 6, 8]
print(random.sample(n,3)) #la fonction sample() donne plusieurs elements




[8, 5, 3]
