In [1]:
import numpy as np 



In [16]:
#les attributs qui composent la calsse ndarray 
data = np.array([[1,3],[5,6],[4,6]])
type(data)
data
data.ndim #connaitre le nombre de  dimensions des axes
data.shape #le tuple qui contient le nombre d'elements pour chaque dimension du tableau
data.size #le nombre de dimensions(axes) 
data.dtype #le types de data des elements 
data.nbytes #l'espace qu'occupe les elements du tableau
#autres formes d'ecriture de la classe ndarray:
# data = np.ndarray(ndim = , dtype = , shape = ,nbytes = , size = ,) 

24

In [38]:
#description basics de chaque attribut: attribut data.type (dtype)
#   int (int8, int16, int32, int64) as integers
#   uint (uint8, uint16, uint32, uint64) as unsigned(negative) integer
#   bool (Bool) as boolean(True or False )
#   float (float16, float32, float64, float128) as floating-point numbers
#   complex( complex64, complex128, complex256) as complex-valued floating-point numbers 
a = np.array([1,2,3,5,6], dtype=np.int)
b = np.array([1,2,3,5,6], dtype = np.float)
c = np.array([1,2,3,5,6], dtype = np.complex)
print(a)
print(b)
print(c)
#operation addition
d = (b+c)
print(d)
#operation puissance 
e = np.sqrt(np.array([-2,0,5, 6], dtype = np.complex)) #il est souvent important de mentionner le type d'ensemble choisi pour  faire loperation.
e


[1 2 3 5 6]
[1. 2. 3. 5. 6.]
[1.+0.j 2.+0.j 3.+0.j 5.+0.j 6.+0.j]
[ 2.+0.j  4.+0.j  6.+0.j 10.+0.j 12.+0.j]


array([0.        +1.41421356j, 0.        +0.j        ,
       2.23606798+0.j        , 2.44948974+0.j        ])